#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceForms
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Flextour")]
	public partial class Trav_ProdDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHRATE(HRATE instance);
    partial void UpdateHRATE(HRATE instance);
    partial void DeleteHRATE(HRATE instance);
    #endregion
		
		public Trav_ProdDataContext() : 
				base(global::TraceForms.Properties.Settings.Default.FlextourConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Trav_ProdDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Trav_ProdDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Trav_ProdDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Trav_ProdDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HRATE> HRATEs
		{
			get
			{
				return this.GetTable<HRATE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HRATES")]
	public partial class HRATE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CODE;
		
		private string _CAT;
		
		private System.Nullable<char> _H_L;
		
		private System.Nullable<int> _YEAR;
		
		private System.Nullable<System.DateTime> _LAST_UPD;
		
		private string _UPD_INIT;
		
		private System.Nullable<System.DateTime> _START_DATE;
		
		private System.Nullable<System.DateTime> _END_DATE;
		
		private string _RATE_DESC;
		
		private System.Nullable<float> _SGL_GRATE;
		
		private System.Nullable<float> _SGL_NRATE;
		
		private System.Nullable<float> _DBL_GRATE;
		
		private System.Nullable<float> _DBL_NRATE;
		
		private System.Nullable<float> _TPL_GRATE;
		
		private System.Nullable<float> _TPL_NRATE;
		
		private System.Nullable<float> _OTH_GRATE;
		
		private System.Nullable<float> _OTH_NRATE;
		
		private System.Nullable<float> _QUA_GRATE;
		
		private System.Nullable<float> _QUA_NRATE;
		
		private System.Nullable<float> _CHD_GRATE;
		
		private System.Nullable<float> _CHD_NRATE;
		
		private string _CHD_LIMIT;
		
		private System.Nullable<float> _JR_GRATE;
		
		private System.Nullable<float> _JR_NRATE;
		
		private string _JR_LIMIT;
		
		private string _MEAL1_CODE;
		
		private System.Nullable<float> _MEAL1_ADG;
		
		private System.Nullable<float> _MEAL1_ADN;
		
		private string _MEAL2_CODE;
		
		private System.Nullable<float> _MEAL2_ADG;
		
		private System.Nullable<float> _MEAL2_ADN;
		
		private string _MEAL3_CODE;
		
		private System.Nullable<float> _MEAL3_ADG;
		
		private System.Nullable<float> _MEAL3_ADN;
		
		private string _MEAL4_CODE;
		
		private System.Nullable<float> _MEAL4_ADG;
		
		private System.Nullable<float> _MEAL4_ADN;
		
		private string _MEAL5_CODE;
		
		private System.Nullable<float> _MEAL5_ADG;
		
		private System.Nullable<float> _MEAL5_ADN;
		
		private string _COMMENT1;
		
		private string _COMMENT2;
		
		private string _AGENCY;
		
		private System.Nullable<char> _COMM_FLG;
		
		private System.Nullable<float> _COMM_PCT;
		
		private System.Nullable<float> _SSGL_GRATE;
		
		private System.Nullable<float> _SSGL_NRATE;
		
		private System.Nullable<float> _SDBL_GRATE;
		
		private System.Nullable<float> _SDBL_NRATE;
		
		private System.Nullable<float> _STPL_GRATE;
		
		private System.Nullable<float> _STPL_NRATE;
		
		private System.Nullable<float> _SOTH_GRATE;
		
		private System.Nullable<float> _SOTH_NRATE;
		
		private System.Nullable<float> _SQUA_GRATE;
		
		private System.Nullable<float> _SQUA_NRATE;
		
		private System.Nullable<float> _SCHD_GRATE;
		
		private System.Nullable<float> _SCHD_NRATE;
		
		private string _SCHD_LIMIT;
		
		private System.Nullable<float> _SJR_GRATE;
		
		private System.Nullable<float> _SJR_NRATE;
		
		private string _SJR_LIMIT;
		
		private System.Nullable<float> _SMEAL1_ADG;
		
		private System.Nullable<float> _SMEAL1_ADN;
		
		private System.Nullable<float> _SMEAL2_ADG;
		
		private System.Nullable<float> _SMEAL2_ADN;
		
		private System.Nullable<float> _SMEAL3_ADG;
		
		private System.Nullable<float> _SMEAL3_ADN;
		
		private System.Nullable<float> _SMEAL4_ADG;
		
		private System.Nullable<float> _SMEAL4_ADN;
		
		private System.Nullable<float> _SMEAL5_ADG;
		
		private System.Nullable<float> _SMEAL5_ADN;
		
		private System.Nullable<char> _SCOMM_FLG;
		
		private System.Nullable<float> _SCOMM_PCT;
		
		private System.Nullable<char> _SUN_FLG;
		
		private System.Nullable<char> _MON_FLG;
		
		private System.Nullable<char> _TUE_FLG;
		
		private System.Nullable<char> _WED_FLG;
		
		private System.Nullable<char> _THU_FLG;
		
		private System.Nullable<char> _FRI_FLG;
		
		private System.Nullable<char> _SAT_FLG;
		
		private System.Nullable<float> _OVRCOMM_PCT;
		
		private System.Nullable<short> _MAX_SGL;
		
		private System.Nullable<short> _MAX_DBL;
		
		private System.Nullable<short> _MAX_TPL;
		
		private System.Nullable<short> _MAX_QUA;
		
		private System.Nullable<short> _MAX_OTH;
		
		private System.Nullable<short> _NightsStay;
		
		private System.Nullable<short> _NightsPay;
		
		private System.Nullable<System.DateTime> _ResDate_Start;
		
		private System.Nullable<System.DateTime> _ResDate_End;
		
		private bool _Inactive;
		
		private System.Nullable<short> _RepeatCount;
		
		private bool _Inhouse;
		
		private string _SpecialValue_Code;
		
		private string _Currency_CodeSheet;
		
		private string _Currency_CodePayment;
		
		private System.Nullable<double> _ExchangeRate;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnCATChanging(string value);
    partial void OnCATChanged();
    partial void OnH_LChanging(System.Nullable<char> value);
    partial void OnH_LChanged();
    partial void OnYEARChanging(System.Nullable<int> value);
    partial void OnYEARChanged();
    partial void OnLAST_UPDChanging(System.Nullable<System.DateTime> value);
    partial void OnLAST_UPDChanged();
    partial void OnUPD_INITChanging(string value);
    partial void OnUPD_INITChanged();
    partial void OnSTART_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTART_DATEChanged();
    partial void OnEND_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEND_DATEChanged();
    partial void OnRATE_DESCChanging(string value);
    partial void OnRATE_DESCChanged();
    partial void OnSGL_GRATEChanging(System.Nullable<float> value);
    partial void OnSGL_GRATEChanged();
    partial void OnSGL_NRATEChanging(System.Nullable<float> value);
    partial void OnSGL_NRATEChanged();
    partial void OnDBL_GRATEChanging(System.Nullable<float> value);
    partial void OnDBL_GRATEChanged();
    partial void OnDBL_NRATEChanging(System.Nullable<float> value);
    partial void OnDBL_NRATEChanged();
    partial void OnTPL_GRATEChanging(System.Nullable<float> value);
    partial void OnTPL_GRATEChanged();
    partial void OnTPL_NRATEChanging(System.Nullable<float> value);
    partial void OnTPL_NRATEChanged();
    partial void OnOTH_GRATEChanging(System.Nullable<float> value);
    partial void OnOTH_GRATEChanged();
    partial void OnOTH_NRATEChanging(System.Nullable<float> value);
    partial void OnOTH_NRATEChanged();
    partial void OnQUA_GRATEChanging(System.Nullable<float> value);
    partial void OnQUA_GRATEChanged();
    partial void OnQUA_NRATEChanging(System.Nullable<float> value);
    partial void OnQUA_NRATEChanged();
    partial void OnCHD_GRATEChanging(System.Nullable<float> value);
    partial void OnCHD_GRATEChanged();
    partial void OnCHD_NRATEChanging(System.Nullable<float> value);
    partial void OnCHD_NRATEChanged();
    partial void OnCHD_LIMITChanging(string value);
    partial void OnCHD_LIMITChanged();
    partial void OnJR_GRATEChanging(System.Nullable<float> value);
    partial void OnJR_GRATEChanged();
    partial void OnJR_NRATEChanging(System.Nullable<float> value);
    partial void OnJR_NRATEChanged();
    partial void OnJR_LIMITChanging(string value);
    partial void OnJR_LIMITChanged();
    partial void OnMEAL1_CODEChanging(string value);
    partial void OnMEAL1_CODEChanged();
    partial void OnMEAL1_ADGChanging(System.Nullable<float> value);
    partial void OnMEAL1_ADGChanged();
    partial void OnMEAL1_ADNChanging(System.Nullable<float> value);
    partial void OnMEAL1_ADNChanged();
    partial void OnMEAL2_CODEChanging(string value);
    partial void OnMEAL2_CODEChanged();
    partial void OnMEAL2_ADGChanging(System.Nullable<float> value);
    partial void OnMEAL2_ADGChanged();
    partial void OnMEAL2_ADNChanging(System.Nullable<float> value);
    partial void OnMEAL2_ADNChanged();
    partial void OnMEAL3_CODEChanging(string value);
    partial void OnMEAL3_CODEChanged();
    partial void OnMEAL3_ADGChanging(System.Nullable<float> value);
    partial void OnMEAL3_ADGChanged();
    partial void OnMEAL3_ADNChanging(System.Nullable<float> value);
    partial void OnMEAL3_ADNChanged();
    partial void OnMEAL4_CODEChanging(string value);
    partial void OnMEAL4_CODEChanged();
    partial void OnMEAL4_ADGChanging(System.Nullable<float> value);
    partial void OnMEAL4_ADGChanged();
    partial void OnMEAL4_ADNChanging(System.Nullable<float> value);
    partial void OnMEAL4_ADNChanged();
    partial void OnMEAL5_CODEChanging(string value);
    partial void OnMEAL5_CODEChanged();
    partial void OnMEAL5_ADGChanging(System.Nullable<float> value);
    partial void OnMEAL5_ADGChanged();
    partial void OnMEAL5_ADNChanging(System.Nullable<float> value);
    partial void OnMEAL5_ADNChanged();
    partial void OnCOMMENT1Changing(string value);
    partial void OnCOMMENT1Changed();
    partial void OnCOMMENT2Changing(string value);
    partial void OnCOMMENT2Changed();
    partial void OnAGENCYChanging(string value);
    partial void OnAGENCYChanged();
    partial void OnCOMM_FLGChanging(System.Nullable<char> value);
    partial void OnCOMM_FLGChanged();
    partial void OnCOMM_PCTChanging(System.Nullable<float> value);
    partial void OnCOMM_PCTChanged();
    partial void OnSSGL_GRATEChanging(System.Nullable<float> value);
    partial void OnSSGL_GRATEChanged();
    partial void OnSSGL_NRATEChanging(System.Nullable<float> value);
    partial void OnSSGL_NRATEChanged();
    partial void OnSDBL_GRATEChanging(System.Nullable<float> value);
    partial void OnSDBL_GRATEChanged();
    partial void OnSDBL_NRATEChanging(System.Nullable<float> value);
    partial void OnSDBL_NRATEChanged();
    partial void OnSTPL_GRATEChanging(System.Nullable<float> value);
    partial void OnSTPL_GRATEChanged();
    partial void OnSTPL_NRATEChanging(System.Nullable<float> value);
    partial void OnSTPL_NRATEChanged();
    partial void OnSOTH_GRATEChanging(System.Nullable<float> value);
    partial void OnSOTH_GRATEChanged();
    partial void OnSOTH_NRATEChanging(System.Nullable<float> value);
    partial void OnSOTH_NRATEChanged();
    partial void OnSQUA_GRATEChanging(System.Nullable<float> value);
    partial void OnSQUA_GRATEChanged();
    partial void OnSQUA_NRATEChanging(System.Nullable<float> value);
    partial void OnSQUA_NRATEChanged();
    partial void OnSCHD_GRATEChanging(System.Nullable<float> value);
    partial void OnSCHD_GRATEChanged();
    partial void OnSCHD_NRATEChanging(System.Nullable<float> value);
    partial void OnSCHD_NRATEChanged();
    partial void OnSCHD_LIMITChanging(string value);
    partial void OnSCHD_LIMITChanged();
    partial void OnSJR_GRATEChanging(System.Nullable<float> value);
    partial void OnSJR_GRATEChanged();
    partial void OnSJR_NRATEChanging(System.Nullable<float> value);
    partial void OnSJR_NRATEChanged();
    partial void OnSJR_LIMITChanging(string value);
    partial void OnSJR_LIMITChanged();
    partial void OnSMEAL1_ADGChanging(System.Nullable<float> value);
    partial void OnSMEAL1_ADGChanged();
    partial void OnSMEAL1_ADNChanging(System.Nullable<float> value);
    partial void OnSMEAL1_ADNChanged();
    partial void OnSMEAL2_ADGChanging(System.Nullable<float> value);
    partial void OnSMEAL2_ADGChanged();
    partial void OnSMEAL2_ADNChanging(System.Nullable<float> value);
    partial void OnSMEAL2_ADNChanged();
    partial void OnSMEAL3_ADGChanging(System.Nullable<float> value);
    partial void OnSMEAL3_ADGChanged();
    partial void OnSMEAL3_ADNChanging(System.Nullable<float> value);
    partial void OnSMEAL3_ADNChanged();
    partial void OnSMEAL4_ADGChanging(System.Nullable<float> value);
    partial void OnSMEAL4_ADGChanged();
    partial void OnSMEAL4_ADNChanging(System.Nullable<float> value);
    partial void OnSMEAL4_ADNChanged();
    partial void OnSMEAL5_ADGChanging(System.Nullable<float> value);
    partial void OnSMEAL5_ADGChanged();
    partial void OnSMEAL5_ADNChanging(System.Nullable<float> value);
    partial void OnSMEAL5_ADNChanged();
    partial void OnSCOMM_FLGChanging(System.Nullable<char> value);
    partial void OnSCOMM_FLGChanged();
    partial void OnSCOMM_PCTChanging(System.Nullable<float> value);
    partial void OnSCOMM_PCTChanged();
    partial void OnSUN_FLGChanging(System.Nullable<char> value);
    partial void OnSUN_FLGChanged();
    partial void OnMON_FLGChanging(System.Nullable<char> value);
    partial void OnMON_FLGChanged();
    partial void OnTUE_FLGChanging(System.Nullable<char> value);
    partial void OnTUE_FLGChanged();
    partial void OnWED_FLGChanging(System.Nullable<char> value);
    partial void OnWED_FLGChanged();
    partial void OnTHU_FLGChanging(System.Nullable<char> value);
    partial void OnTHU_FLGChanged();
    partial void OnFRI_FLGChanging(System.Nullable<char> value);
    partial void OnFRI_FLGChanged();
    partial void OnSAT_FLGChanging(System.Nullable<char> value);
    partial void OnSAT_FLGChanged();
    partial void OnOVRCOMM_PCTChanging(System.Nullable<float> value);
    partial void OnOVRCOMM_PCTChanged();
    partial void OnMAX_SGLChanging(System.Nullable<short> value);
    partial void OnMAX_SGLChanged();
    partial void OnMAX_DBLChanging(System.Nullable<short> value);
    partial void OnMAX_DBLChanged();
    partial void OnMAX_TPLChanging(System.Nullable<short> value);
    partial void OnMAX_TPLChanged();
    partial void OnMAX_QUAChanging(System.Nullable<short> value);
    partial void OnMAX_QUAChanged();
    partial void OnMAX_OTHChanging(System.Nullable<short> value);
    partial void OnMAX_OTHChanged();
    partial void OnNightsStayChanging(System.Nullable<short> value);
    partial void OnNightsStayChanged();
    partial void OnNightsPayChanging(System.Nullable<short> value);
    partial void OnNightsPayChanged();
    partial void OnResDate_StartChanging(System.Nullable<System.DateTime> value);
    partial void OnResDate_StartChanged();
    partial void OnResDate_EndChanging(System.Nullable<System.DateTime> value);
    partial void OnResDate_EndChanged();
    partial void OnInactiveChanging(bool value);
    partial void OnInactiveChanged();
    partial void OnRepeatCountChanging(System.Nullable<short> value);
    partial void OnRepeatCountChanged();
    partial void OnInhouseChanging(bool value);
    partial void OnInhouseChanged();
    partial void OnSpecialValue_CodeChanging(string value);
    partial void OnSpecialValue_CodeChanged();
    partial void OnCurrency_CodeSheetChanging(string value);
    partial void OnCurrency_CodeSheetChanged();
    partial void OnCurrency_CodePaymentChanging(string value);
    partial void OnCurrency_CodePaymentChanged();
    partial void OnExchangeRateChanging(System.Nullable<double> value);
    partial void OnExchangeRateChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public HRATE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="Char(8)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAT", DbType="Char(3)")]
		public string CAT
		{
			get
			{
				return this._CAT;
			}
			set
			{
				if ((this._CAT != value))
				{
					this.OnCATChanging(value);
					this.SendPropertyChanging();
					this._CAT = value;
					this.SendPropertyChanged("CAT");
					this.OnCATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[H L]", Storage="_H_L", DbType="Char(1)")]
		public System.Nullable<char> H_L
		{
			get
			{
				return this._H_L;
			}
			set
			{
				if ((this._H_L != value))
				{
					this.OnH_LChanging(value);
					this.SendPropertyChanging();
					this._H_L = value;
					this.SendPropertyChanged("H_L");
					this.OnH_LChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="Int")]
		public System.Nullable<int> YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this.OnYEARChanging(value);
					this.SendPropertyChanging();
					this._YEAR = value;
					this.SendPropertyChanged("YEAR");
					this.OnYEARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[LAST UPD]", Storage="_LAST_UPD", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> LAST_UPD
		{
			get
			{
				return this._LAST_UPD;
			}
			set
			{
				if ((this._LAST_UPD != value))
				{
					this.OnLAST_UPDChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPD = value;
					this.SendPropertyChanged("LAST_UPD");
					this.OnLAST_UPDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[UPD INIT]", Storage="_UPD_INIT", DbType="Char(3)")]
		public string UPD_INIT
		{
			get
			{
				return this._UPD_INIT;
			}
			set
			{
				if ((this._UPD_INIT != value))
				{
					this.OnUPD_INITChanging(value);
					this.SendPropertyChanging();
					this._UPD_INIT = value;
					this.SendPropertyChanged("UPD_INIT");
					this.OnUPD_INITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[START DATE]", Storage="_START_DATE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> START_DATE
		{
			get
			{
				return this._START_DATE;
			}
			set
			{
				if ((this._START_DATE != value))
				{
					this.OnSTART_DATEChanging(value);
					this.SendPropertyChanging();
					this._START_DATE = value;
					this.SendPropertyChanged("START_DATE");
					this.OnSTART_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[END DATE]", Storage="_END_DATE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> END_DATE
		{
			get
			{
				return this._END_DATE;
			}
			set
			{
				if ((this._END_DATE != value))
				{
					this.OnEND_DATEChanging(value);
					this.SendPropertyChanging();
					this._END_DATE = value;
					this.SendPropertyChanged("END_DATE");
					this.OnEND_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[RATE DESC]", Storage="_RATE_DESC", DbType="Char(30)")]
		public string RATE_DESC
		{
			get
			{
				return this._RATE_DESC;
			}
			set
			{
				if ((this._RATE_DESC != value))
				{
					this.OnRATE_DESCChanging(value);
					this.SendPropertyChanging();
					this._RATE_DESC = value;
					this.SendPropertyChanged("RATE_DESC");
					this.OnRATE_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SGL GRATE]", Storage="_SGL_GRATE", DbType="Real")]
		public System.Nullable<float> SGL_GRATE
		{
			get
			{
				return this._SGL_GRATE;
			}
			set
			{
				if ((this._SGL_GRATE != value))
				{
					this.OnSGL_GRATEChanging(value);
					this.SendPropertyChanging();
					this._SGL_GRATE = value;
					this.SendPropertyChanged("SGL_GRATE");
					this.OnSGL_GRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SGL NRATE]", Storage="_SGL_NRATE", DbType="Real")]
		public System.Nullable<float> SGL_NRATE
		{
			get
			{
				return this._SGL_NRATE;
			}
			set
			{
				if ((this._SGL_NRATE != value))
				{
					this.OnSGL_NRATEChanging(value);
					this.SendPropertyChanging();
					this._SGL_NRATE = value;
					this.SendPropertyChanged("SGL_NRATE");
					this.OnSGL_NRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DBL GRATE]", Storage="_DBL_GRATE", DbType="Real")]
		public System.Nullable<float> DBL_GRATE
		{
			get
			{
				return this._DBL_GRATE;
			}
			set
			{
				if ((this._DBL_GRATE != value))
				{
					this.OnDBL_GRATEChanging(value);
					this.SendPropertyChanging();
					this._DBL_GRATE = value;
					this.SendPropertyChanged("DBL_GRATE");
					this.OnDBL_GRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DBL NRATE]", Storage="_DBL_NRATE", DbType="Real")]
		public System.Nullable<float> DBL_NRATE
		{
			get
			{
				return this._DBL_NRATE;
			}
			set
			{
				if ((this._DBL_NRATE != value))
				{
					this.OnDBL_NRATEChanging(value);
					this.SendPropertyChanging();
					this._DBL_NRATE = value;
					this.SendPropertyChanged("DBL_NRATE");
					this.OnDBL_NRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TPL GRATE]", Storage="_TPL_GRATE", DbType="Real")]
		public System.Nullable<float> TPL_GRATE
		{
			get
			{
				return this._TPL_GRATE;
			}
			set
			{
				if ((this._TPL_GRATE != value))
				{
					this.OnTPL_GRATEChanging(value);
					this.SendPropertyChanging();
					this._TPL_GRATE = value;
					this.SendPropertyChanged("TPL_GRATE");
					this.OnTPL_GRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TPL NRATE]", Storage="_TPL_NRATE", DbType="Real")]
		public System.Nullable<float> TPL_NRATE
		{
			get
			{
				return this._TPL_NRATE;
			}
			set
			{
				if ((this._TPL_NRATE != value))
				{
					this.OnTPL_NRATEChanging(value);
					this.SendPropertyChanging();
					this._TPL_NRATE = value;
					this.SendPropertyChanged("TPL_NRATE");
					this.OnTPL_NRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[OTH GRATE]", Storage="_OTH_GRATE", DbType="Real")]
		public System.Nullable<float> OTH_GRATE
		{
			get
			{
				return this._OTH_GRATE;
			}
			set
			{
				if ((this._OTH_GRATE != value))
				{
					this.OnOTH_GRATEChanging(value);
					this.SendPropertyChanging();
					this._OTH_GRATE = value;
					this.SendPropertyChanged("OTH_GRATE");
					this.OnOTH_GRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[OTH NRATE]", Storage="_OTH_NRATE", DbType="Real")]
		public System.Nullable<float> OTH_NRATE
		{
			get
			{
				return this._OTH_NRATE;
			}
			set
			{
				if ((this._OTH_NRATE != value))
				{
					this.OnOTH_NRATEChanging(value);
					this.SendPropertyChanging();
					this._OTH_NRATE = value;
					this.SendPropertyChanged("OTH_NRATE");
					this.OnOTH_NRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[QUA GRATE]", Storage="_QUA_GRATE", DbType="Real")]
		public System.Nullable<float> QUA_GRATE
		{
			get
			{
				return this._QUA_GRATE;
			}
			set
			{
				if ((this._QUA_GRATE != value))
				{
					this.OnQUA_GRATEChanging(value);
					this.SendPropertyChanging();
					this._QUA_GRATE = value;
					this.SendPropertyChanged("QUA_GRATE");
					this.OnQUA_GRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[QUA NRATE]", Storage="_QUA_NRATE", DbType="Real")]
		public System.Nullable<float> QUA_NRATE
		{
			get
			{
				return this._QUA_NRATE;
			}
			set
			{
				if ((this._QUA_NRATE != value))
				{
					this.OnQUA_NRATEChanging(value);
					this.SendPropertyChanging();
					this._QUA_NRATE = value;
					this.SendPropertyChanged("QUA_NRATE");
					this.OnQUA_NRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CHD GRATE]", Storage="_CHD_GRATE", DbType="Real")]
		public System.Nullable<float> CHD_GRATE
		{
			get
			{
				return this._CHD_GRATE;
			}
			set
			{
				if ((this._CHD_GRATE != value))
				{
					this.OnCHD_GRATEChanging(value);
					this.SendPropertyChanging();
					this._CHD_GRATE = value;
					this.SendPropertyChanged("CHD_GRATE");
					this.OnCHD_GRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CHD NRATE]", Storage="_CHD_NRATE", DbType="Real")]
		public System.Nullable<float> CHD_NRATE
		{
			get
			{
				return this._CHD_NRATE;
			}
			set
			{
				if ((this._CHD_NRATE != value))
				{
					this.OnCHD_NRATEChanging(value);
					this.SendPropertyChanging();
					this._CHD_NRATE = value;
					this.SendPropertyChanged("CHD_NRATE");
					this.OnCHD_NRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CHD LIMIT]", Storage="_CHD_LIMIT", DbType="Char(15)")]
		public string CHD_LIMIT
		{
			get
			{
				return this._CHD_LIMIT;
			}
			set
			{
				if ((this._CHD_LIMIT != value))
				{
					this.OnCHD_LIMITChanging(value);
					this.SendPropertyChanging();
					this._CHD_LIMIT = value;
					this.SendPropertyChanged("CHD_LIMIT");
					this.OnCHD_LIMITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[JR GRATE]", Storage="_JR_GRATE", DbType="Real")]
		public System.Nullable<float> JR_GRATE
		{
			get
			{
				return this._JR_GRATE;
			}
			set
			{
				if ((this._JR_GRATE != value))
				{
					this.OnJR_GRATEChanging(value);
					this.SendPropertyChanging();
					this._JR_GRATE = value;
					this.SendPropertyChanged("JR_GRATE");
					this.OnJR_GRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[JR NRATE]", Storage="_JR_NRATE", DbType="Real")]
		public System.Nullable<float> JR_NRATE
		{
			get
			{
				return this._JR_NRATE;
			}
			set
			{
				if ((this._JR_NRATE != value))
				{
					this.OnJR_NRATEChanging(value);
					this.SendPropertyChanging();
					this._JR_NRATE = value;
					this.SendPropertyChanged("JR_NRATE");
					this.OnJR_NRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[JR LIMIT]", Storage="_JR_LIMIT", DbType="Char(15)")]
		public string JR_LIMIT
		{
			get
			{
				return this._JR_LIMIT;
			}
			set
			{
				if ((this._JR_LIMIT != value))
				{
					this.OnJR_LIMITChanging(value);
					this.SendPropertyChanging();
					this._JR_LIMIT = value;
					this.SendPropertyChanged("JR_LIMIT");
					this.OnJR_LIMITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL1 CODE]", Storage="_MEAL1_CODE", DbType="Char(3)")]
		public string MEAL1_CODE
		{
			get
			{
				return this._MEAL1_CODE;
			}
			set
			{
				if ((this._MEAL1_CODE != value))
				{
					this.OnMEAL1_CODEChanging(value);
					this.SendPropertyChanging();
					this._MEAL1_CODE = value;
					this.SendPropertyChanged("MEAL1_CODE");
					this.OnMEAL1_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL1 ADG]", Storage="_MEAL1_ADG", DbType="Real")]
		public System.Nullable<float> MEAL1_ADG
		{
			get
			{
				return this._MEAL1_ADG;
			}
			set
			{
				if ((this._MEAL1_ADG != value))
				{
					this.OnMEAL1_ADGChanging(value);
					this.SendPropertyChanging();
					this._MEAL1_ADG = value;
					this.SendPropertyChanged("MEAL1_ADG");
					this.OnMEAL1_ADGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL1 ADN]", Storage="_MEAL1_ADN", DbType="Real")]
		public System.Nullable<float> MEAL1_ADN
		{
			get
			{
				return this._MEAL1_ADN;
			}
			set
			{
				if ((this._MEAL1_ADN != value))
				{
					this.OnMEAL1_ADNChanging(value);
					this.SendPropertyChanging();
					this._MEAL1_ADN = value;
					this.SendPropertyChanged("MEAL1_ADN");
					this.OnMEAL1_ADNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL2 CODE]", Storage="_MEAL2_CODE", DbType="Char(3)")]
		public string MEAL2_CODE
		{
			get
			{
				return this._MEAL2_CODE;
			}
			set
			{
				if ((this._MEAL2_CODE != value))
				{
					this.OnMEAL2_CODEChanging(value);
					this.SendPropertyChanging();
					this._MEAL2_CODE = value;
					this.SendPropertyChanged("MEAL2_CODE");
					this.OnMEAL2_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL2 ADG]", Storage="_MEAL2_ADG", DbType="Real")]
		public System.Nullable<float> MEAL2_ADG
		{
			get
			{
				return this._MEAL2_ADG;
			}
			set
			{
				if ((this._MEAL2_ADG != value))
				{
					this.OnMEAL2_ADGChanging(value);
					this.SendPropertyChanging();
					this._MEAL2_ADG = value;
					this.SendPropertyChanged("MEAL2_ADG");
					this.OnMEAL2_ADGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL2 ADN]", Storage="_MEAL2_ADN", DbType="Real")]
		public System.Nullable<float> MEAL2_ADN
		{
			get
			{
				return this._MEAL2_ADN;
			}
			set
			{
				if ((this._MEAL2_ADN != value))
				{
					this.OnMEAL2_ADNChanging(value);
					this.SendPropertyChanging();
					this._MEAL2_ADN = value;
					this.SendPropertyChanged("MEAL2_ADN");
					this.OnMEAL2_ADNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL3 CODE]", Storage="_MEAL3_CODE", DbType="Char(3)")]
		public string MEAL3_CODE
		{
			get
			{
				return this._MEAL3_CODE;
			}
			set
			{
				if ((this._MEAL3_CODE != value))
				{
					this.OnMEAL3_CODEChanging(value);
					this.SendPropertyChanging();
					this._MEAL3_CODE = value;
					this.SendPropertyChanged("MEAL3_CODE");
					this.OnMEAL3_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL3 ADG]", Storage="_MEAL3_ADG", DbType="Real")]
		public System.Nullable<float> MEAL3_ADG
		{
			get
			{
				return this._MEAL3_ADG;
			}
			set
			{
				if ((this._MEAL3_ADG != value))
				{
					this.OnMEAL3_ADGChanging(value);
					this.SendPropertyChanging();
					this._MEAL3_ADG = value;
					this.SendPropertyChanged("MEAL3_ADG");
					this.OnMEAL3_ADGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL3 ADN]", Storage="_MEAL3_ADN", DbType="Real")]
		public System.Nullable<float> MEAL3_ADN
		{
			get
			{
				return this._MEAL3_ADN;
			}
			set
			{
				if ((this._MEAL3_ADN != value))
				{
					this.OnMEAL3_ADNChanging(value);
					this.SendPropertyChanging();
					this._MEAL3_ADN = value;
					this.SendPropertyChanged("MEAL3_ADN");
					this.OnMEAL3_ADNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL4 CODE]", Storage="_MEAL4_CODE", DbType="Char(3)")]
		public string MEAL4_CODE
		{
			get
			{
				return this._MEAL4_CODE;
			}
			set
			{
				if ((this._MEAL4_CODE != value))
				{
					this.OnMEAL4_CODEChanging(value);
					this.SendPropertyChanging();
					this._MEAL4_CODE = value;
					this.SendPropertyChanged("MEAL4_CODE");
					this.OnMEAL4_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL4 ADG]", Storage="_MEAL4_ADG", DbType="Real")]
		public System.Nullable<float> MEAL4_ADG
		{
			get
			{
				return this._MEAL4_ADG;
			}
			set
			{
				if ((this._MEAL4_ADG != value))
				{
					this.OnMEAL4_ADGChanging(value);
					this.SendPropertyChanging();
					this._MEAL4_ADG = value;
					this.SendPropertyChanged("MEAL4_ADG");
					this.OnMEAL4_ADGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL4 ADN]", Storage="_MEAL4_ADN", DbType="Real")]
		public System.Nullable<float> MEAL4_ADN
		{
			get
			{
				return this._MEAL4_ADN;
			}
			set
			{
				if ((this._MEAL4_ADN != value))
				{
					this.OnMEAL4_ADNChanging(value);
					this.SendPropertyChanging();
					this._MEAL4_ADN = value;
					this.SendPropertyChanged("MEAL4_ADN");
					this.OnMEAL4_ADNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL5 CODE]", Storage="_MEAL5_CODE", DbType="Char(3)")]
		public string MEAL5_CODE
		{
			get
			{
				return this._MEAL5_CODE;
			}
			set
			{
				if ((this._MEAL5_CODE != value))
				{
					this.OnMEAL5_CODEChanging(value);
					this.SendPropertyChanging();
					this._MEAL5_CODE = value;
					this.SendPropertyChanged("MEAL5_CODE");
					this.OnMEAL5_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL5 ADG]", Storage="_MEAL5_ADG", DbType="Real")]
		public System.Nullable<float> MEAL5_ADG
		{
			get
			{
				return this._MEAL5_ADG;
			}
			set
			{
				if ((this._MEAL5_ADG != value))
				{
					this.OnMEAL5_ADGChanging(value);
					this.SendPropertyChanging();
					this._MEAL5_ADG = value;
					this.SendPropertyChanged("MEAL5_ADG");
					this.OnMEAL5_ADGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MEAL5 ADN]", Storage="_MEAL5_ADN", DbType="Real")]
		public System.Nullable<float> MEAL5_ADN
		{
			get
			{
				return this._MEAL5_ADN;
			}
			set
			{
				if ((this._MEAL5_ADN != value))
				{
					this.OnMEAL5_ADNChanging(value);
					this.SendPropertyChanging();
					this._MEAL5_ADN = value;
					this.SendPropertyChanged("MEAL5_ADN");
					this.OnMEAL5_ADNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENT1", DbType="Char(35)")]
		public string COMMENT1
		{
			get
			{
				return this._COMMENT1;
			}
			set
			{
				if ((this._COMMENT1 != value))
				{
					this.OnCOMMENT1Changing(value);
					this.SendPropertyChanging();
					this._COMMENT1 = value;
					this.SendPropertyChanged("COMMENT1");
					this.OnCOMMENT1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENT2", DbType="Char(35)")]
		public string COMMENT2
		{
			get
			{
				return this._COMMENT2;
			}
			set
			{
				if ((this._COMMENT2 != value))
				{
					this.OnCOMMENT2Changing(value);
					this.SendPropertyChanging();
					this._COMMENT2 = value;
					this.SendPropertyChanged("COMMENT2");
					this.OnCOMMENT2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGENCY", DbType="Char(10)")]
		public string AGENCY
		{
			get
			{
				return this._AGENCY;
			}
			set
			{
				if ((this._AGENCY != value))
				{
					this.OnAGENCYChanging(value);
					this.SendPropertyChanging();
					this._AGENCY = value;
					this.SendPropertyChanged("AGENCY");
					this.OnAGENCYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[COMM FLG]", Storage="_COMM_FLG", DbType="Char(1)")]
		public System.Nullable<char> COMM_FLG
		{
			get
			{
				return this._COMM_FLG;
			}
			set
			{
				if ((this._COMM_FLG != value))
				{
					this.OnCOMM_FLGChanging(value);
					this.SendPropertyChanging();
					this._COMM_FLG = value;
					this.SendPropertyChanged("COMM_FLG");
					this.OnCOMM_FLGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[COMM PCT]", Storage="_COMM_PCT", DbType="Real")]
		public System.Nullable<float> COMM_PCT
		{
			get
			{
				return this._COMM_PCT;
			}
			set
			{
				if ((this._COMM_PCT != value))
				{
					this.OnCOMM_PCTChanging(value);
					this.SendPropertyChanging();
					this._COMM_PCT = value;
					this.SendPropertyChanged("COMM_PCT");
					this.OnCOMM_PCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SSGL GRATE]", Storage="_SSGL_GRATE", DbType="Real")]
		public System.Nullable<float> SSGL_GRATE
		{
			get
			{
				return this._SSGL_GRATE;
			}
			set
			{
				if ((this._SSGL_GRATE != value))
				{
					this.OnSSGL_GRATEChanging(value);
					this.SendPropertyChanging();
					this._SSGL_GRATE = value;
					this.SendPropertyChanged("SSGL_GRATE");
					this.OnSSGL_GRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SSGL NRATE]", Storage="_SSGL_NRATE", DbType="Real")]
		public System.Nullable<float> SSGL_NRATE
		{
			get
			{
				return this._SSGL_NRATE;
			}
			set
			{
				if ((this._SSGL_NRATE != value))
				{
					this.OnSSGL_NRATEChanging(value);
					this.SendPropertyChanging();
					this._SSGL_NRATE = value;
					this.SendPropertyChanged("SSGL_NRATE");
					this.OnSSGL_NRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SDBL GRATE]", Storage="_SDBL_GRATE", DbType="Real")]
		public System.Nullable<float> SDBL_GRATE
		{
			get
			{
				return this._SDBL_GRATE;
			}
			set
			{
				if ((this._SDBL_GRATE != value))
				{
					this.OnSDBL_GRATEChanging(value);
					this.SendPropertyChanging();
					this._SDBL_GRATE = value;
					this.SendPropertyChanged("SDBL_GRATE");
					this.OnSDBL_GRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SDBL NRATE]", Storage="_SDBL_NRATE", DbType="Real")]
		public System.Nullable<float> SDBL_NRATE
		{
			get
			{
				return this._SDBL_NRATE;
			}
			set
			{
				if ((this._SDBL_NRATE != value))
				{
					this.OnSDBL_NRATEChanging(value);
					this.SendPropertyChanging();
					this._SDBL_NRATE = value;
					this.SendPropertyChanged("SDBL_NRATE");
					this.OnSDBL_NRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[STPL GRATE]", Storage="_STPL_GRATE", DbType="Real")]
		public System.Nullable<float> STPL_GRATE
		{
			get
			{
				return this._STPL_GRATE;
			}
			set
			{
				if ((this._STPL_GRATE != value))
				{
					this.OnSTPL_GRATEChanging(value);
					this.SendPropertyChanging();
					this._STPL_GRATE = value;
					this.SendPropertyChanged("STPL_GRATE");
					this.OnSTPL_GRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[STPL NRATE]", Storage="_STPL_NRATE", DbType="Real")]
		public System.Nullable<float> STPL_NRATE
		{
			get
			{
				return this._STPL_NRATE;
			}
			set
			{
				if ((this._STPL_NRATE != value))
				{
					this.OnSTPL_NRATEChanging(value);
					this.SendPropertyChanging();
					this._STPL_NRATE = value;
					this.SendPropertyChanged("STPL_NRATE");
					this.OnSTPL_NRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SOTH GRATE]", Storage="_SOTH_GRATE", DbType="Real")]
		public System.Nullable<float> SOTH_GRATE
		{
			get
			{
				return this._SOTH_GRATE;
			}
			set
			{
				if ((this._SOTH_GRATE != value))
				{
					this.OnSOTH_GRATEChanging(value);
					this.SendPropertyChanging();
					this._SOTH_GRATE = value;
					this.SendPropertyChanged("SOTH_GRATE");
					this.OnSOTH_GRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SOTH NRATE]", Storage="_SOTH_NRATE", DbType="Real")]
		public System.Nullable<float> SOTH_NRATE
		{
			get
			{
				return this._SOTH_NRATE;
			}
			set
			{
				if ((this._SOTH_NRATE != value))
				{
					this.OnSOTH_NRATEChanging(value);
					this.SendPropertyChanging();
					this._SOTH_NRATE = value;
					this.SendPropertyChanged("SOTH_NRATE");
					this.OnSOTH_NRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SQUA GRATE]", Storage="_SQUA_GRATE", DbType="Real")]
		public System.Nullable<float> SQUA_GRATE
		{
			get
			{
				return this._SQUA_GRATE;
			}
			set
			{
				if ((this._SQUA_GRATE != value))
				{
					this.OnSQUA_GRATEChanging(value);
					this.SendPropertyChanging();
					this._SQUA_GRATE = value;
					this.SendPropertyChanged("SQUA_GRATE");
					this.OnSQUA_GRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SQUA NRATE]", Storage="_SQUA_NRATE", DbType="Real")]
		public System.Nullable<float> SQUA_NRATE
		{
			get
			{
				return this._SQUA_NRATE;
			}
			set
			{
				if ((this._SQUA_NRATE != value))
				{
					this.OnSQUA_NRATEChanging(value);
					this.SendPropertyChanging();
					this._SQUA_NRATE = value;
					this.SendPropertyChanged("SQUA_NRATE");
					this.OnSQUA_NRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SCHD GRATE]", Storage="_SCHD_GRATE", DbType="Real")]
		public System.Nullable<float> SCHD_GRATE
		{
			get
			{
				return this._SCHD_GRATE;
			}
			set
			{
				if ((this._SCHD_GRATE != value))
				{
					this.OnSCHD_GRATEChanging(value);
					this.SendPropertyChanging();
					this._SCHD_GRATE = value;
					this.SendPropertyChanged("SCHD_GRATE");
					this.OnSCHD_GRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SCHD NRATE]", Storage="_SCHD_NRATE", DbType="Real")]
		public System.Nullable<float> SCHD_NRATE
		{
			get
			{
				return this._SCHD_NRATE;
			}
			set
			{
				if ((this._SCHD_NRATE != value))
				{
					this.OnSCHD_NRATEChanging(value);
					this.SendPropertyChanging();
					this._SCHD_NRATE = value;
					this.SendPropertyChanged("SCHD_NRATE");
					this.OnSCHD_NRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SCHD LIMIT]", Storage="_SCHD_LIMIT", DbType="Char(15)")]
		public string SCHD_LIMIT
		{
			get
			{
				return this._SCHD_LIMIT;
			}
			set
			{
				if ((this._SCHD_LIMIT != value))
				{
					this.OnSCHD_LIMITChanging(value);
					this.SendPropertyChanging();
					this._SCHD_LIMIT = value;
					this.SendPropertyChanged("SCHD_LIMIT");
					this.OnSCHD_LIMITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SJR GRATE]", Storage="_SJR_GRATE", DbType="Real")]
		public System.Nullable<float> SJR_GRATE
		{
			get
			{
				return this._SJR_GRATE;
			}
			set
			{
				if ((this._SJR_GRATE != value))
				{
					this.OnSJR_GRATEChanging(value);
					this.SendPropertyChanging();
					this._SJR_GRATE = value;
					this.SendPropertyChanged("SJR_GRATE");
					this.OnSJR_GRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SJR NRATE]", Storage="_SJR_NRATE", DbType="Real")]
		public System.Nullable<float> SJR_NRATE
		{
			get
			{
				return this._SJR_NRATE;
			}
			set
			{
				if ((this._SJR_NRATE != value))
				{
					this.OnSJR_NRATEChanging(value);
					this.SendPropertyChanging();
					this._SJR_NRATE = value;
					this.SendPropertyChanged("SJR_NRATE");
					this.OnSJR_NRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SJR LIMIT]", Storage="_SJR_LIMIT", DbType="Char(15)")]
		public string SJR_LIMIT
		{
			get
			{
				return this._SJR_LIMIT;
			}
			set
			{
				if ((this._SJR_LIMIT != value))
				{
					this.OnSJR_LIMITChanging(value);
					this.SendPropertyChanging();
					this._SJR_LIMIT = value;
					this.SendPropertyChanged("SJR_LIMIT");
					this.OnSJR_LIMITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SMEAL1 ADG]", Storage="_SMEAL1_ADG", DbType="Real")]
		public System.Nullable<float> SMEAL1_ADG
		{
			get
			{
				return this._SMEAL1_ADG;
			}
			set
			{
				if ((this._SMEAL1_ADG != value))
				{
					this.OnSMEAL1_ADGChanging(value);
					this.SendPropertyChanging();
					this._SMEAL1_ADG = value;
					this.SendPropertyChanged("SMEAL1_ADG");
					this.OnSMEAL1_ADGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SMEAL1 ADN]", Storage="_SMEAL1_ADN", DbType="Real")]
		public System.Nullable<float> SMEAL1_ADN
		{
			get
			{
				return this._SMEAL1_ADN;
			}
			set
			{
				if ((this._SMEAL1_ADN != value))
				{
					this.OnSMEAL1_ADNChanging(value);
					this.SendPropertyChanging();
					this._SMEAL1_ADN = value;
					this.SendPropertyChanged("SMEAL1_ADN");
					this.OnSMEAL1_ADNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SMEAL2 ADG]", Storage="_SMEAL2_ADG", DbType="Real")]
		public System.Nullable<float> SMEAL2_ADG
		{
			get
			{
				return this._SMEAL2_ADG;
			}
			set
			{
				if ((this._SMEAL2_ADG != value))
				{
					this.OnSMEAL2_ADGChanging(value);
					this.SendPropertyChanging();
					this._SMEAL2_ADG = value;
					this.SendPropertyChanged("SMEAL2_ADG");
					this.OnSMEAL2_ADGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SMEAL2 ADN]", Storage="_SMEAL2_ADN", DbType="Real")]
		public System.Nullable<float> SMEAL2_ADN
		{
			get
			{
				return this._SMEAL2_ADN;
			}
			set
			{
				if ((this._SMEAL2_ADN != value))
				{
					this.OnSMEAL2_ADNChanging(value);
					this.SendPropertyChanging();
					this._SMEAL2_ADN = value;
					this.SendPropertyChanged("SMEAL2_ADN");
					this.OnSMEAL2_ADNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SMEAL3 ADG]", Storage="_SMEAL3_ADG", DbType="Real")]
		public System.Nullable<float> SMEAL3_ADG
		{
			get
			{
				return this._SMEAL3_ADG;
			}
			set
			{
				if ((this._SMEAL3_ADG != value))
				{
					this.OnSMEAL3_ADGChanging(value);
					this.SendPropertyChanging();
					this._SMEAL3_ADG = value;
					this.SendPropertyChanged("SMEAL3_ADG");
					this.OnSMEAL3_ADGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SMEAL3 ADN]", Storage="_SMEAL3_ADN", DbType="Real")]
		public System.Nullable<float> SMEAL3_ADN
		{
			get
			{
				return this._SMEAL3_ADN;
			}
			set
			{
				if ((this._SMEAL3_ADN != value))
				{
					this.OnSMEAL3_ADNChanging(value);
					this.SendPropertyChanging();
					this._SMEAL3_ADN = value;
					this.SendPropertyChanged("SMEAL3_ADN");
					this.OnSMEAL3_ADNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SMEAL4 ADG]", Storage="_SMEAL4_ADG", DbType="Real")]
		public System.Nullable<float> SMEAL4_ADG
		{
			get
			{
				return this._SMEAL4_ADG;
			}
			set
			{
				if ((this._SMEAL4_ADG != value))
				{
					this.OnSMEAL4_ADGChanging(value);
					this.SendPropertyChanging();
					this._SMEAL4_ADG = value;
					this.SendPropertyChanged("SMEAL4_ADG");
					this.OnSMEAL4_ADGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SMEAL4 ADN]", Storage="_SMEAL4_ADN", DbType="Real")]
		public System.Nullable<float> SMEAL4_ADN
		{
			get
			{
				return this._SMEAL4_ADN;
			}
			set
			{
				if ((this._SMEAL4_ADN != value))
				{
					this.OnSMEAL4_ADNChanging(value);
					this.SendPropertyChanging();
					this._SMEAL4_ADN = value;
					this.SendPropertyChanged("SMEAL4_ADN");
					this.OnSMEAL4_ADNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SMEAL5 ADG]", Storage="_SMEAL5_ADG", DbType="Real")]
		public System.Nullable<float> SMEAL5_ADG
		{
			get
			{
				return this._SMEAL5_ADG;
			}
			set
			{
				if ((this._SMEAL5_ADG != value))
				{
					this.OnSMEAL5_ADGChanging(value);
					this.SendPropertyChanging();
					this._SMEAL5_ADG = value;
					this.SendPropertyChanged("SMEAL5_ADG");
					this.OnSMEAL5_ADGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SMEAL5 ADN]", Storage="_SMEAL5_ADN", DbType="Real")]
		public System.Nullable<float> SMEAL5_ADN
		{
			get
			{
				return this._SMEAL5_ADN;
			}
			set
			{
				if ((this._SMEAL5_ADN != value))
				{
					this.OnSMEAL5_ADNChanging(value);
					this.SendPropertyChanging();
					this._SMEAL5_ADN = value;
					this.SendPropertyChanged("SMEAL5_ADN");
					this.OnSMEAL5_ADNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SCOMM FLG]", Storage="_SCOMM_FLG", DbType="Char(1)")]
		public System.Nullable<char> SCOMM_FLG
		{
			get
			{
				return this._SCOMM_FLG;
			}
			set
			{
				if ((this._SCOMM_FLG != value))
				{
					this.OnSCOMM_FLGChanging(value);
					this.SendPropertyChanging();
					this._SCOMM_FLG = value;
					this.SendPropertyChanged("SCOMM_FLG");
					this.OnSCOMM_FLGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SCOMM PCT]", Storage="_SCOMM_PCT", DbType="Real")]
		public System.Nullable<float> SCOMM_PCT
		{
			get
			{
				return this._SCOMM_PCT;
			}
			set
			{
				if ((this._SCOMM_PCT != value))
				{
					this.OnSCOMM_PCTChanging(value);
					this.SendPropertyChanging();
					this._SCOMM_PCT = value;
					this.SendPropertyChanged("SCOMM_PCT");
					this.OnSCOMM_PCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SUN FLG]", Storage="_SUN_FLG", DbType="Char(1)")]
		public System.Nullable<char> SUN_FLG
		{
			get
			{
				return this._SUN_FLG;
			}
			set
			{
				if ((this._SUN_FLG != value))
				{
					this.OnSUN_FLGChanging(value);
					this.SendPropertyChanging();
					this._SUN_FLG = value;
					this.SendPropertyChanged("SUN_FLG");
					this.OnSUN_FLGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MON FLG]", Storage="_MON_FLG", DbType="Char(1)")]
		public System.Nullable<char> MON_FLG
		{
			get
			{
				return this._MON_FLG;
			}
			set
			{
				if ((this._MON_FLG != value))
				{
					this.OnMON_FLGChanging(value);
					this.SendPropertyChanging();
					this._MON_FLG = value;
					this.SendPropertyChanged("MON_FLG");
					this.OnMON_FLGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TUE FLG]", Storage="_TUE_FLG", DbType="Char(1)")]
		public System.Nullable<char> TUE_FLG
		{
			get
			{
				return this._TUE_FLG;
			}
			set
			{
				if ((this._TUE_FLG != value))
				{
					this.OnTUE_FLGChanging(value);
					this.SendPropertyChanging();
					this._TUE_FLG = value;
					this.SendPropertyChanged("TUE_FLG");
					this.OnTUE_FLGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[WED FLG]", Storage="_WED_FLG", DbType="Char(1)")]
		public System.Nullable<char> WED_FLG
		{
			get
			{
				return this._WED_FLG;
			}
			set
			{
				if ((this._WED_FLG != value))
				{
					this.OnWED_FLGChanging(value);
					this.SendPropertyChanging();
					this._WED_FLG = value;
					this.SendPropertyChanged("WED_FLG");
					this.OnWED_FLGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[THU FLG]", Storage="_THU_FLG", DbType="Char(1)")]
		public System.Nullable<char> THU_FLG
		{
			get
			{
				return this._THU_FLG;
			}
			set
			{
				if ((this._THU_FLG != value))
				{
					this.OnTHU_FLGChanging(value);
					this.SendPropertyChanging();
					this._THU_FLG = value;
					this.SendPropertyChanged("THU_FLG");
					this.OnTHU_FLGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[FRI FLG]", Storage="_FRI_FLG", DbType="Char(1)")]
		public System.Nullable<char> FRI_FLG
		{
			get
			{
				return this._FRI_FLG;
			}
			set
			{
				if ((this._FRI_FLG != value))
				{
					this.OnFRI_FLGChanging(value);
					this.SendPropertyChanging();
					this._FRI_FLG = value;
					this.SendPropertyChanged("FRI_FLG");
					this.OnFRI_FLGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SAT FLG]", Storage="_SAT_FLG", DbType="Char(1)")]
		public System.Nullable<char> SAT_FLG
		{
			get
			{
				return this._SAT_FLG;
			}
			set
			{
				if ((this._SAT_FLG != value))
				{
					this.OnSAT_FLGChanging(value);
					this.SendPropertyChanging();
					this._SAT_FLG = value;
					this.SendPropertyChanged("SAT_FLG");
					this.OnSAT_FLGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[OVRCOMM PCT]", Storage="_OVRCOMM_PCT", DbType="Real")]
		public System.Nullable<float> OVRCOMM_PCT
		{
			get
			{
				return this._OVRCOMM_PCT;
			}
			set
			{
				if ((this._OVRCOMM_PCT != value))
				{
					this.OnOVRCOMM_PCTChanging(value);
					this.SendPropertyChanging();
					this._OVRCOMM_PCT = value;
					this.SendPropertyChanged("OVRCOMM_PCT");
					this.OnOVRCOMM_PCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAX SGL]", Storage="_MAX_SGL", DbType="SmallInt")]
		public System.Nullable<short> MAX_SGL
		{
			get
			{
				return this._MAX_SGL;
			}
			set
			{
				if ((this._MAX_SGL != value))
				{
					this.OnMAX_SGLChanging(value);
					this.SendPropertyChanging();
					this._MAX_SGL = value;
					this.SendPropertyChanged("MAX_SGL");
					this.OnMAX_SGLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAX DBL]", Storage="_MAX_DBL", DbType="SmallInt")]
		public System.Nullable<short> MAX_DBL
		{
			get
			{
				return this._MAX_DBL;
			}
			set
			{
				if ((this._MAX_DBL != value))
				{
					this.OnMAX_DBLChanging(value);
					this.SendPropertyChanging();
					this._MAX_DBL = value;
					this.SendPropertyChanged("MAX_DBL");
					this.OnMAX_DBLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAX TPL]", Storage="_MAX_TPL", DbType="SmallInt")]
		public System.Nullable<short> MAX_TPL
		{
			get
			{
				return this._MAX_TPL;
			}
			set
			{
				if ((this._MAX_TPL != value))
				{
					this.OnMAX_TPLChanging(value);
					this.SendPropertyChanging();
					this._MAX_TPL = value;
					this.SendPropertyChanged("MAX_TPL");
					this.OnMAX_TPLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAX QUA]", Storage="_MAX_QUA", DbType="SmallInt")]
		public System.Nullable<short> MAX_QUA
		{
			get
			{
				return this._MAX_QUA;
			}
			set
			{
				if ((this._MAX_QUA != value))
				{
					this.OnMAX_QUAChanging(value);
					this.SendPropertyChanging();
					this._MAX_QUA = value;
					this.SendPropertyChanged("MAX_QUA");
					this.OnMAX_QUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAX OTH]", Storage="_MAX_OTH", DbType="SmallInt")]
		public System.Nullable<short> MAX_OTH
		{
			get
			{
				return this._MAX_OTH;
			}
			set
			{
				if ((this._MAX_OTH != value))
				{
					this.OnMAX_OTHChanging(value);
					this.SendPropertyChanging();
					this._MAX_OTH = value;
					this.SendPropertyChanged("MAX_OTH");
					this.OnMAX_OTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NightsStay", DbType="SmallInt")]
		public System.Nullable<short> NightsStay
		{
			get
			{
				return this._NightsStay;
			}
			set
			{
				if ((this._NightsStay != value))
				{
					this.OnNightsStayChanging(value);
					this.SendPropertyChanging();
					this._NightsStay = value;
					this.SendPropertyChanged("NightsStay");
					this.OnNightsStayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NightsPay", DbType="SmallInt")]
		public System.Nullable<short> NightsPay
		{
			get
			{
				return this._NightsPay;
			}
			set
			{
				if ((this._NightsPay != value))
				{
					this.OnNightsPayChanging(value);
					this.SendPropertyChanging();
					this._NightsPay = value;
					this.SendPropertyChanged("NightsPay");
					this.OnNightsPayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResDate_Start", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ResDate_Start
		{
			get
			{
				return this._ResDate_Start;
			}
			set
			{
				if ((this._ResDate_Start != value))
				{
					this.OnResDate_StartChanging(value);
					this.SendPropertyChanging();
					this._ResDate_Start = value;
					this.SendPropertyChanged("ResDate_Start");
					this.OnResDate_StartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResDate_End", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ResDate_End
		{
			get
			{
				return this._ResDate_End;
			}
			set
			{
				if ((this._ResDate_End != value))
				{
					this.OnResDate_EndChanging(value);
					this.SendPropertyChanging();
					this._ResDate_End = value;
					this.SendPropertyChanged("ResDate_End");
					this.OnResDate_EndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inactive", DbType="Bit NOT NULL")]
		public bool Inactive
		{
			get
			{
				return this._Inactive;
			}
			set
			{
				if ((this._Inactive != value))
				{
					this.OnInactiveChanging(value);
					this.SendPropertyChanging();
					this._Inactive = value;
					this.SendPropertyChanged("Inactive");
					this.OnInactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepeatCount", DbType="SmallInt")]
		public System.Nullable<short> RepeatCount
		{
			get
			{
				return this._RepeatCount;
			}
			set
			{
				if ((this._RepeatCount != value))
				{
					this.OnRepeatCountChanging(value);
					this.SendPropertyChanging();
					this._RepeatCount = value;
					this.SendPropertyChanged("RepeatCount");
					this.OnRepeatCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inhouse", DbType="Bit NOT NULL")]
		public bool Inhouse
		{
			get
			{
				return this._Inhouse;
			}
			set
			{
				if ((this._Inhouse != value))
				{
					this.OnInhouseChanging(value);
					this.SendPropertyChanging();
					this._Inhouse = value;
					this.SendPropertyChanged("Inhouse");
					this.OnInhouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecialValue_Code", DbType="Char(8)")]
		public string SpecialValue_Code
		{
			get
			{
				return this._SpecialValue_Code;
			}
			set
			{
				if ((this._SpecialValue_Code != value))
				{
					this.OnSpecialValue_CodeChanging(value);
					this.SendPropertyChanging();
					this._SpecialValue_Code = value;
					this.SendPropertyChanged("SpecialValue_Code");
					this.OnSpecialValue_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency_CodeSheet", DbType="Char(3)")]
		public string Currency_CodeSheet
		{
			get
			{
				return this._Currency_CodeSheet;
			}
			set
			{
				if ((this._Currency_CodeSheet != value))
				{
					this.OnCurrency_CodeSheetChanging(value);
					this.SendPropertyChanging();
					this._Currency_CodeSheet = value;
					this.SendPropertyChanged("Currency_CodeSheet");
					this.OnCurrency_CodeSheetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency_CodePayment", DbType="Char(3)")]
		public string Currency_CodePayment
		{
			get
			{
				return this._Currency_CodePayment;
			}
			set
			{
				if ((this._Currency_CodePayment != value))
				{
					this.OnCurrency_CodePaymentChanging(value);
					this.SendPropertyChanging();
					this._Currency_CodePayment = value;
					this.SendPropertyChanged("Currency_CodePayment");
					this.OnCurrency_CodePaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExchangeRate", DbType="Float")]
		public System.Nullable<double> ExchangeRate
		{
			get
			{
				return this._ExchangeRate;
			}
			set
			{
				if ((this._ExchangeRate != value))
				{
					this.OnExchangeRateChanging(value);
					this.SendPropertyChanging();
					this._ExchangeRate = value;
					this.SendPropertyChanged("ExchangeRate");
					this.OnExchangeRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
